version: '3.9'

services:
  database:
    image: postgres
    container_name: db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - data:/var/lib/postgresql/data
      - logs:/var/lib/postgresql/logs
    networks:
      - home-network

  app:
    image: nestapp
    container_name: app
    build: ./
    restart: always
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/nestapp/src/
    depends_on:
      - database
    networks:
      - home-network

volumes:
  logs:
  data:

networks:
  home-network:
    driver: bridge