version: '3.8'
services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - home_library_network

  nestapp:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    volumes:
      - .:/nestapp/src
    networks:
      - home_library_network

networks:
  home_library_network:
    driver: bridge

volumes:
  postgres_data:
  postgres_logs:
  nestapp:
    driver: local