version: '3.8'
services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - home_library_network

volumes:
  postgres:

  nestApp:
    build: .
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db_home_library
    depends_on:
      - postgres
    networks:
      - home_library_network

networks:
  home_library_network:
    driver: bridge